### ISSUE TITLE
No way to go back after clicking on meeting in Repository

### ISSUE THREAD

**Issue by zackharley** [ColinLMacLeod1/MonetaMVP#12]
**Issue**
After clicking on one of my meetings in my Repository, I am unable to navigate back to the initial Repository screen; therefore, I am unable to view my other meetings without refreshing the site.

**Screenshot**
<img width="1680" alt="screen shot 2017-08-14 at 9 44 24 pm" src="https://user-images.githubusercontent.com/13260302/29299020-d46cb312-8139-11e7-8442-f52c45bb9869.png">

**Comment by tdeoliveira05** [comment]
possible error caused by title being too long, added overflow: auto to allow title to scroll instead of overlapping sidebar, seems fixed
