### ISSUE TITLE
Long strings overflow second meeting screen

### ISSUE THREAD

**Issue by zackharley** [ColinLMacLeod1/MonetaMVP#4]
**Issue**
Long strings overflow second meeting screen

**Screenshot**
<img width="839" alt="screen shot 2017-08-13 at 11 29 12 pm" src="https://user-images.githubusercontent.com/13260302/29257377-843b3b08-807f-11e7-8ec7-e175bba8d6dd.png">

**Comment by andrewlitt** [comment]
Done!

**Comment by zackharley** [comment]
@andrewlitt You may want to consider instituting a character limit on the input as removing overflow for the text container stops the whole name of the meeting from being shown. If you really need to abruptly cut off the text, then the `text-overflow` CSS property might be a more elegant solution. (See https://www.w3schools.com/cssref/css3_pr_text-overflow.asp)

**Comment by zackharley** [comment]
Also, the change you made to fix this on the repo screen causes the whole container to overflow

<img width="1049" alt="screen shot 2017-08-14 at 9 43 42 pm" src="https://user-images.githubusercontent.com/13260302/29298996-add7df56-8139-11e7-8362-8fb565e1c48a.png">

**Comment by tdeoliveira05** [comment]
overflow: scroll to deal with error, issue opened for character limit
