### ISSUE TITLE
Every time you click save when creating a meeting a new repo entry is created

### ISSUE THREAD

**Issue by zackharley** [ColinLMacLeod1/MonetaMVP#9]
**Issue**
When creating a meeting, I clicked Save 3 times and was never redirected from the create a meeting page as I would have assumed. I looked under the Repository tab and saw that I have the 3 meetings

**Comment by tdeoliveira05** [comment]
when user clicks "save & finish" they are redirected out of that page with a snack bar indicating a successful save!
